var mongoose = require("mongoose");
var Mix = require("./models/mixes");

var data = [{"Name":"Bo-Dach","breed1":"Dachshund","breed2":"Boston Terrier","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Bo-Dach.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Chiweenie","breed1":"Dachshund","breed2":"Chihuahua","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Chiweenie.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Dameranian","breed1":"Dachshund","breed2":"Pomeranian","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Dameranian.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Daug","breed1":"Dachshund","breed2":"Pug","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Daug.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Dorgi","breed1":"Dachshund","breed2":"Corgi","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Dorgi.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Dorkie","breed1":"Dachshund","breed2":"Yorkshire Terrier","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Dorkie.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Doxador","breed1":"Dachshund","breed2":"Labrador Retriever","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Doxador.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Golden Dox","breed1":"Dachshund","breed2":"Golden Retriever","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Golden-Dox.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Papshund","breed1":"Dachshund","breed2":"Papillon","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Papshund.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Shibadox","breed1":"Dachshund","breed2":"Shiba Inu","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Shibadox.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Doxle","breed1":"Dachshund","breed2":"Beagle","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/02/4e60be815c84133f85bc36cc91d965d4.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Dorgi","breed1":"Dachshund","breed2":"Corgi","image":"http://www.101dogbreeds.com/wp-content/uploads/2015/05/Dorgi.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/34-unreal-dachshund-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Corgherd","breed1":"Corgi","breed2":"Australian Shepherd","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/6/asset/buzzfeed-prod-web11/sub-buzz-2448-1468406006-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Labragi","breed1":"Corgi","breed2":"Labrador Retriever","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/6/asset/buzzfeed-prod-web13/sub-buzz-23761-1468406410-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"German Shephergi","breed1":"Corgi","breed2":"German Shepherd","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/6/asset/buzzfeed-prod-web13/sub-buzz-24434-1468407414-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Beagi","breed1":"Corgi","breed2":"Beagle","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/6/asset/buzzfeed-prod-web11/sub-buzz-3255-1468406994-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Shigi","breed1":"Corgi","breed2":"Shiba Inu","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/7/asset/buzzfeed-prod-web15/sub-buzz-21877-1468408023-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Cohuahua","breed1":"Corgi","breed2":"Chihuahua","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/6/asset/buzzfeed-prod-web05/sub-buzz-30503-1468407584-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Corgiever","breed1":"Corgi","breed2":"Golden Retriever","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/6/asset/buzzfeed-prod-web04/sub-buzz-2081-1468406865-2.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Greygi","breed1":"Corgi","breed2":"Greyhound","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/7/asset/buzzfeed-prod-web12/sub-buzz-29139-1468407952-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Pitgi","breed1":"Corgi","breed2":"Pit Bull","image":"https://img.buzzfeed.com/buzzfeed-static/static/2016-07/13/7/asset/buzzfeed-prod-web08/sub-buzz-30375-1468408228-1.png?downsize=715:*&output-format=auto&output-quality=auto","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Corgeranian","breed1":"Corgi","breed2":"Pomeranian","image":"http://static.boredpanda.com/blog/wp-content/uploads/2017/05/corgi-mix-cross-breeds-1-591998b9a867f__605.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Chowrgi","breed1":"Corgi","breed2":"Chow Chow","image":"http://static.boredpanda.com/blog/wp-content/uploads/2017/05/corgi-mix-cross-breeds-2-591b02bbf338f__605.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Alaskan Corgi","breed1":"Corgi","breed2":"Alaskan Malamute","image":"http://static.boredpanda.com/blog/wp-content/uploads/2017/05/591c51134240f_UC8srbW__605.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"https://www.buzzfeed.com/karstenschmehl/corgi-hybrids?utm_term=.hiDq252zX#.yxwWkQka7"},
{"Name":"Pomtease","breed1":"Maltese","breed2":"Pomeranian","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/pom-maltese-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/13-gorgeous-maltese-mixes-and-their-ludicrous-names/#gs.nE9XFVk"},
{"Name":"Perkintease","breed1":"Maltese","breed2":"Pekingese","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/perkingese-maltese.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/13-gorgeous-maltese-mixes-and-their-ludicrous-names/#gs.nE9XFVk"},
{"Name":"Malterrier","breed1":"Maltese","breed2":"Yorkshire Terrier","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/yorkie-x-maltese.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/13-gorgeous-maltese-mixes-and-their-ludicrous-names/#gs.nE9XFVk"},
{"Name":"Malteagle","breed1":"Maltese","breed2":"Beagle","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/malti-beagle-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/13-gorgeous-maltese-mixes-and-their-ludicrous-names/#gs.nE9XFVk"},
{"Name":"Mug","breed1":"Maltese","breed2":"Pug","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/malti-pug.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/13-gorgeous-maltese-mixes-and-their-ludicrous-names/#gs.nE9XFVk"},
{"Name":"Papimalt","breed1":"Maltese","breed2":"Papillon","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/papillon-maltese.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/13-gorgeous-maltese-mixes-and-their-ludicrous-names/#gs.nE9XFVk"},
{"Name":"Russell Pug","breed1":"Pug","breed2":"Jack Russell Terrier","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/478c680d80eadb81a50fe1aeaa4d9e5a.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/10-of-the-most-peculiar-but-absolutely-gorgeous-pug-mixes-you-need-to-see/"},
{"Name":"Shipug","breed1":"Pug","breed2":"Shiba Inu","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/pug-shiba-Inu-BowWow-Times.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/10-of-the-most-peculiar-but-absolutely-gorgeous-pug-mixes-you-need-to-see/"},
{"Name":"Le Pugdog","breed1":"Pug","breed2":"French Bulldog","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/pug-and-french-bulldog.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/10-of-the-most-peculiar-but-absolutely-gorgeous-pug-mixes-you-need-to-see/"},
{"Name":"Dachpug","breed1":"Pug","breed2":"Dachshund","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/pug-dachshund-mix-cross.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/10-of-the-most-peculiar-but-absolutely-gorgeous-pug-mixes-you-need-to-see/"},
{"Name":"Pugle","breed1":"Pug","breed2":"Beagle","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/pug-beagle.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/10-of-the-most-peculiar-but-absolutely-gorgeous-pug-mixes-you-need-to-see/"},
{"Name":"Pugterrier","breed1":"Pug","breed2":"Yorkshire Terrier","image":"https://s3-eu-west-1.amazonaws.com/bowwowtimes-new/wp-content/uploads/2015/08/pug-yorkshire-terrier.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.holidogtimes.com/10-of-the-most-peculiar-but-absolutely-gorgeous-pug-mixes-you-need-to-see/"},
{"Name":"Australian Pug","breed1":"Pug","breed2":"Australian Shepherd","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Australian-Shepard-Pug-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/16-unreal-pug-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Pugeranian","breed1":"Pug","breed2":"Pomeranian","image":"http://buzzsharer.com/wp-content/uploads/2015/09/pomeranian-pug-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/16-unreal-pug-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Pughound","breed1":"Pug","breed2":"Basset Hound","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Basset-pug-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/16-unreal-pug-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Boston Pug","breed1":"Pug","breed2":"Boston Terrier","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Pug-and-Boston-Terrier-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/16-unreal-pug-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Boxpug","breed1":"Pug","breed2":"Boxer","image":"http://www.pawbuzz.com/wp-content/uploads/sites/551/2016/04/Poxer-Boxer-Pug.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/16-unreal-pug-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Pugtzu","breed1":"Pug","breed2":"Shih Tzu","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Shih-Tzu-cross-Pug.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/16-unreal-pug-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Boston Bulldog","breed1":"French Bulldog","breed2":"Boston Terrier","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Frenchton.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/10-unreal-french-bulldog-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"French Pitdog","breed1":"French Bulldog","breed2":"Pit Bull","image":"http://buzzsharer.com/wp-content/uploads/2015/09/American-Pitbull-French-Bulldog-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/10-unreal-french-bulldog-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Frenchuahua","breed1":"French Bulldog","breed2":"Chihuahua","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Chihuahua-French-Bulldog-mix1.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/10-unreal-french-bulldog-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Bulldogeagle","breed1":"French Bulldog","breed2":"Beagle","image":"http://buzzsharer.com/wp-content/uploads/2015/09/Beagle-French-Bulldog-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/10-unreal-french-bulldog-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Bulldoganian","breed1":"French Bulldog","breed2":"Pomeranian","image":"http://www.holidogtimes.com/wp-content/uploads/2016/02/pomerfrenchie.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/10-unreal-french-bulldog-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Frenchowow","breed1":"French Bulldog","breed2":"Chow Chow","image":"http://www.holidogtimes.com/fr/wp-content/uploads/sites/2/2016/02/bulldogs-french-breeds-14.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://buzzsharer.com/2015/09/10-unreal-french-bulldog-cross-breeds-you-have-to-see-to-believe/"},
{"Name":"Beager","breed1":"Boxer","breed2":"Beagle","image":"http://www.pawbuzz.com/wp-content/uploads/sites/551/2015/09/boxer-crossbreeds-1-681x1024.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.pawbuzz.com/unreal-boxer-dog-cross-breeds/"},
{"Name":"Boxita","breed1":"Boxer","breed2":"Akita","image":"http://www.pawbuzz.com/wp-content/uploads/sites/551/2015/09/boxer-crossbreeds-3.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.pawbuzz.com/unreal-boxer-dog-cross-breeds/"},
{"Name":"Golden Box","breed1":"Boxer","breed2":"Golden Retriever","image":"http://www.pawbuzz.com/wp-content/uploads/sites/551/2016/04/golden-boxer-2.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.pawbuzz.com/unreal-boxer-dog-cross-breeds/"},
{"Name":"Husker","breed1":"Boxer","breed2":"Husky","image":"http://www.pawbuzz.com/wp-content/uploads/sites/551/2016/04/husky-boxer-mix.jpg","checkAll":"all","upvote":0,"downvote":0,"imagesource":"http://www.pawbuzz.com/unreal-boxer-dog-cross-breeds/"},
{"Name":"Puguaua","breed1":"Pug","breed2":"Chihuahua","image":"https://s-media-cache-ak0.pinimg.com/736x/8b/1a/36/8b1a36a3ed0265dd86b24a3701895dd9.jpg","checkAll":"all","upvote":7,"downvote":14,"imagesource":"https://www.pinterest.com/pin/451345193876599543/"},
{"Name":"Corpug","breed1":"Corgi","breed2":"Pug","image":"http://www.thatcutesite.com/uploads/2011/06/corgi_pug_mix_hybrid_breed.jpg","checkAll":"all","upvote":50,"downvote":19,"imagesource":"http://www.thatcutesite.com/corgi-cross-breeds-are-cute-25-pictures/"},
{"Name":"Husgi","breed1":"Husky","breed2":"Corgi","image":"http://img.photobucket.com/albums/v704/xVelvet_FuzzButtx/3%20Dog%20Night/ShortLegsHalo.jpg","checkAll":"all","upvote":100,"downvote":22,"imagesource":"http://www.dogbreedplus.com/dog_breeds/horgi.php"},
{"Name":"Pitsky","breed1":"Pit Bull","breed2":"Husky","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-27.jpg","checkAll":"all","upvote":150,"downvote":2,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"Corgmation","breed1":"Corgi","breed2":"Dalmation","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-21.jpg","checkAll":"all","upvote":200,"downvote":4,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"Chusky","breed1":"Chow Chow","breed2":"Husky","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-7.jpg","checkAll":"all","upvote":250,"downvote":13,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"Dalmachshund","breed1":"Dachshund","breed2":"Dalmation","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-17.jpg","checkAll":"all","upvote":175,"downvote":45,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"Labsky","breed1":"Labrador Retriever","breed2":"Husky","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-9.jpg","checkAll":"all","upvote":77,"downvote":8,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"German Corgi","breed1":"Corgi","breed2":"German Shepherd","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-6.jpg","checkAll":"all","upvote":99,"downvote":5,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"Pomsky","breed1":"Siberian Husky","breed2":"Pomeranian","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-4.jpg","checkAll":"all","upvote":98,"downvote":4,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"},
{"Name":"Bullpug","breed1":"Pug","breed2":"English Bulldog","image":"http://static.boredpanda.com/blog/wp-content/uploads/2014/03/mixed-breed-dogs-25.jpg","checkAll":"all","upvote":7,"downvote":35,"imagesource":"http://www.boredpanda.com/mixed-breed-dogs/"}]

function seedDB() {
    // Removes all Mixes

    Mix.remove({}, function(err) {
        if (err) {
            console.log(err);
        }
        else {
            console.log("Removed Mixes");
        }
        data.forEach(function(seed) {
            Mix.create(seed, function(err, Mix) {
                if (err) {
                    console.log(err)
                }
                else {
                    console.log("Mix added");
                    //

                }
            });
        });
        //add a few Mixes
    });
}


module.exports = seedDB;