/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%] {\n    display: inline;\n    padding-left: 90px;\n\n}\n\n.larger[_ngcontent-%COMP%] {\n    font-size: 1.2em;\n    color: red;\n}\n\n\n@media (max-width: 1200px) {\n\n  \n.huge.image.label[_ngcontent-%COMP%] {\n    font-size: 1rem !important;\n}\n\n}\n\n@media (max-width: 765px) {\n\n  \n.huge.image.label[_ngcontent-%COMP%] {\n      font-size: 1.42857143rem !important;\n}\n\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdWJ1bnR1L3dvcmtzcGFjZS9tYWluL2Fzc2V0cy9hcHAvc2hvdy1taXgtZGV0YWlsL3Nob3ctbWl4LWRldGFpbC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdWJ1bnR1L3dvcmtzcGFjZS9tYWluL2Fzc2V0cy9hcHAvc2hvdy1taXgtZGV0YWlsL3Nob3ctbWl4LWRldGFpbC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
