/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './about.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../assets/app/about/about.component';
const styles_AboutComponent:any[] = [import0.styles];
export const RenderType_AboutComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_AboutComponent,
  data: {}
}
);
export function View_AboutComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),23,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),20,'div',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),7,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['A display of adorable mixes like the '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'http://mydogmixtape.herokuapp.com/mixes/594dcc486618ef32097d8a3f'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Corgiever'])),
    (l()(),import1.ɵted((null as any),[' and questionable outcomes like the\n            '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'http://mydogmixtape.herokuapp.com/mixes/594dcc486618ef32097d8a51'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Australian Pug'])),
    (l()(),import1.ɵted((null as any),['.'])),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Please help us chart these unknown territories and submit your findings! '])),
    (l()(),import1.ɵted((null as any),['\n\n        '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),0,'img',[[
        'src',
        'http://i.imgur.com/RJHgnht.png'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n        '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),3,'h6',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Icons courtesy of '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'http://www.freepik.com/free-vector/cute-dog-breeds_803197.htm'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Freepik'])),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_AboutComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'about',([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
    import1.ɵdid(114688,(null as any),0,import2.AboutComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AboutComponentNgFactory:import1.ComponentFactory<import2.AboutComponent> = import1.ɵccf('about',import2.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdWJ1bnR1L3dvcmtzcGFjZS9tYWluL2Fzc2V0cy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdWJ1bnR1L3dvcmtzcGFjZS9tYWluL2Fzc2V0cy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS91YnVudHUvd29ya3NwYWNlL21haW4vYXNzZXRzL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdWJ1bnR1L3dvcmtzcGFjZS9tYWluL2Fzc2V0cy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LnRzLkFib3V0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICAgICAgPGg1PkEgZGlzcGxheSBvZiBhZG9yYWJsZSBtaXhlcyBsaWtlIHRoZSA8YSBocmVmPVwiaHR0cDovL215ZG9nbWl4dGFwZS5oZXJva3VhcHAuY29tL21peGVzLzU5NGRjYzQ4NjYxOGVmMzIwOTdkOGEzZlwiPkNvcmdpZXZlcjwvYT4gYW5kIHF1ZXN0aW9uYWJsZSBvdXRjb21lcyBsaWtlIHRoZVxuICAgICAgICAgICAgPGEgaHJlZj1cImh0dHA6Ly9teWRvZ21peHRhcGUuaGVyb2t1YXBwLmNvbS9taXhlcy81OTRkY2M0ODY2MThlZjMyMDk3ZDhhNTFcIj5BdXN0cmFsaWFuIFB1ZzwvYT4uPC9oNT5cbiAgICAgICAgPGg1PlBsZWFzZSBoZWxwIHVzIGNoYXJ0IHRoZXNlIHVua25vd24gdGVycml0b3JpZXMgYW5kIHN1Ym1pdCB5b3VyIGZpbmRpbmdzISA8L2g1PlxuXG4gICAgICAgIDxpbWcgc3JjPVwiaHR0cDovL2kuaW1ndXIuY29tL1JKSGduaHQucG5nXCI+XG4gICAgICAgIDxoNj5JY29ucyBjb3VydGVzeSBvZiA8YSBocmVmPVwiaHR0cDovL3d3dy5mcmVlcGlrLmNvbS9mcmVlLXZlY3Rvci9jdXRlLWRvZy1icmVlZHNfODAzMTk3Lmh0bVwiPkZyZWVwaWs8L2E+PC9oNj5cbiAgICA8L2Rpdj5cbjwvZGl2PiIsIjxhYm91dD48L2Fib3V0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O01DQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtNQUNuQjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXVCO0lBQ25CO0lBQUk7TUFBcUM7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyRTtJQUFhO01BQzdIO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMkU7SUFBa0I7SUFBTTtJQUN2RztJQUFJO0lBQThFO01BRWxGO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMEM7SUFDMUM7SUFBSTtNQUFrQjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXdFO0lBQWdCO0lBQzVHOzs7Ozs7SUNSVjtnQkFBQTs7O0lBQUE7OzsifQ==
