/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['#scroll[_ngcontent-%COMP%] {\n\n    height: 900px;\n    overflow: scroll;\n}\n\n\n  \n    #sidemenu[_ngcontent-%COMP%] {\n    width: 190px;\n  }\n  \n    .fixed.column[_ngcontent-%COMP%] {\n    width: 190px;\n  }\n  \n@media (max-width: 600px) {\n  \n  .fixed.column[_ngcontent-%COMP%] {\n    width: 125px;\n  }\n  #sidemenu[_ngcontent-%COMP%] {\n    width: 125px;\n  }\n\n  .hide-if[_ngcontent-%COMP%]{\n    display: none !important;\n  }\n  \n  .smaller-font[_ngcontent-%COMP%] {\n    font-size:0.8em !important;\n  }\n}\n\n.noCursor[_ngcontent-%COMP%] {\n    cursor: default !important;\n}\n\n.labelColor[_ngcontent-%COMP%] {\n  color: #a7adb7 !important;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdWJ1bnR1L3dvcmtzcGFjZS9tYWluL2Fzc2V0cy9hcHAvc2hvdy1taXhlcy9zaG93LW1peGVzLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS91YnVudHUvd29ya3NwYWNlL21haW4vYXNzZXRzL2FwcC9zaG93LW1peGVzL3Nob3ctbWl4ZXMuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
